# HaskellNet had a last commit in dec 2020! apparently not maintained so stay with smtp-mail
# a lot of the smtp-mail code is based on HaskellNet!
# https://github.com/UnkindPartition/ansi-terminal/issues/114
name:                logging-simple
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/gbwey/logging-simple#readme
license:             BSD3
copyright:           2018 Grant Weyburne
category:            Logging
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - baseutils
  - clock
  - coreutils
  - dhall >= 1.32.0
  - directory
  - docutils
  - fast-logger
  - mime-mail
  - monad-logger
  - mtl
  - pretty-simple
  - prettyprinter
  - smtp-mail
  - text
  - time
  - template-haskell
  - th-lift-instances
  - unix-time
  - unliftio
  - unliftio-core
when:
    - condition: os(windows)
      dependencies: Win32 >= 2.2 && < 2.9

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wredundant-constraints
  - -Wsimplifiable-class-constraints
  - -Wmonomorphism-restriction
  - -Wmissing-deriving-strategies
  - -Wmissing-local-signatures
  - -Widentities
executables:
  perflog:
    buildable: false
    source-dirs:
    - app
    main:             Main.hs
    ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    - -Wmissing-deriving-strategies
    - -Widentities
    - -Wno-missing-local-signatures
    dependencies:
    - base
    - logging-simple
    - criterion

tests:
  logging-simple-test:
    main:                Main.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    - -Wmissing-deriving-strategies
    - -Widentities
    dependencies:
    - base
    - logging-simple
    - generic-lens
    - lens
    - tasty
    - tasty-hunit
