name:                logging-simple
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/gbwey/logging-simple#readme
license:             BSD3
copyright:           2018 Grant Weyburne
category:            Logging
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - clock
  - directory
  - extra
  - fast-logger
  - formatting
  - mime-mail
  - monad-logger
  - mtl
  - smtp-mail
  - text
  - time
  - template-haskell
  - th-lift-instances
  - unix-time
  - unliftio
  - unliftio-core
when:
    - condition: os(windows)
      dependencies: Win32 >= 2.2 && < 2.9

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wredundant-constraints
  when:
   - condition: impl(ghc >= 8.8)
     ghc-options:
     - -fwrite-ide-info
     - -hiedir=.hie
     - -Widentities

executables:
  perflog:
    buildable: false
    source-dirs:
    - app
    main:             Main.hs
    ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    when:
       condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie
       - -Widentities
    dependencies:
    - base
    - logging-simple
    - criterion

